CC     = gcc
CFLAGS = -lm -lcrypt -O2 -pipe -ansi -DONLINE_JUDGE

#------------------------------------------------------------------------------
.PHONY: default clean

default: the_3n+1_problem.c
	$(CC) $(CFLAGS) -o the_3n+1_problem the_3n+1_problem.c

clean:
	@$(RM) -v the_3n+1_problem
